# Workspace cleanup detection for MnemoCetus (v0.5 Stage B - MnemoClean's detect-and-measure half).
#
# The scan filters regenerable bloat (RECLAIMABLE_MARKERS) out of a project; this module still SIZES those dirs so we can tell the user how much disk is reclaimable.
# Detection only: it never deletes anything (the recommendations layer lives in db_manager.cleanup_recommendations).

import os

from scanner import _is_excluded  # reuse the scan's exclusion test, so "excluded but not reclaimable" (e.g. .git) is handled identically

# Directories the scan filters out but that we still want to SIZE, because they're regenerable: delete them and a tool rebuilds them. 
# Each entry: dir name -> (kind, how it comes back).
# This is deliberately a curated set (not the whole exclude list) -> things like .git are excluded from scans too, but they are NOT reclaimable, so they must never show up as a "mark".
RECLAIMABLE_MARKERS = {
    "node_modules":   ("dependencies", "npm / yarn / pnpm install"),
    "vendor":         ("dependencies", "go mod / composer install"),
    "venv":           ("virtualenv", "python -m venv"),
    ".venv":          ("virtualenv", "python -m venv"),
    "__pycache__":    ("cache", "regenerated by Python"),
    ".pytest_cache":  ("cache", "regenerated by pytest"),
    ".mypy_cache":    ("cache", "regenerated by mypy"),
    ".ruff_cache":    ("cache", "regenerated by ruff"),
    ".tox":           ("cache", "regenerated by tox"),
    ".gradle":        ("cache", "regenerated by Gradle"),
    ".cache":         ("cache", "rebuildable cache"),
    "target":         ("build", "cargo / maven build"),
    "dist":           ("build", "build output"),
    "build":          ("build", "build output"),
    ".next":          ("build", "next build"),
    ".nuxt":          ("build", "nuxt build"),
    ".svelte-kit":    ("build", "svelte-kit build"),
}

def _dir_size(path):
    """Total (size_bytes, file_count) of a directory subtree -> a 'du' used to weigh a mark."""
    total_bytes = total_files = 0
    for root, _dirs, files in os.walk(path):
        for f in files:
            try:
                total_bytes += os.path.getsize(os.path.join(root, f))
                total_files += 1
            except OSError:
                continue
    return total_bytes, total_files

def _collect_marks(directory, name_rules, path_rules):
    """
    Walk the given 'directory' and flag every regenerable/bloat subtree (as seen in RECLAIMABLE_MARKERS) that the normal scan filters out, additionally sizing each one so we can tell the user how much disk is reclaimable.

    A reclaimable dir is measured whole (we 'du' it) and then NOT descended into.
    Other excluded or hidden dirs are skipped just like the scan skips them -> but they're not marks, so they aren't sized.

    Args:
        directory (str): the project dir to inspect.
        name_rules (set): compiled basename exclude rules (to skip non-reclaimable excluded dirs).
        path_rules (set): compiled path exclude rules.

    Returns:
        list[dict]: one {kind, name, path, size_bytes, file_count, reason} per reclaimable dir found.
    """
    marks = []
    for root, dirs, files in os.walk(directory):
        keep = []
        for d in dirs:
            full = os.path.join(root, d)
            marker = RECLAIMABLE_MARKERS.get(d)
            if marker:
                kind, reason = marker
                size, count = _dir_size(full)
                marks.append({
                    "kind": kind, "name": d, "path": os.path.normpath(full),
                    "size_bytes": size, "file_count": count, "reason": reason,
                })
                continue  # measured the whole subtree -> don't descend into it
            if d.startswith('.') or _is_excluded(full, name_rules, path_rules):
                continue  # excluded/hidden but not reclaimable (e.g. .git) -> skip, don't mark
            keep.append(d)
        dirs[:] = keep
    return marks
